### ISSUE TITLE
Cannot be installed on Win10 via pip

### ISSUE THREAD

**Issue by Scrooge20291224** [kmaork/hypno#2]
hypno/injection.c(3): fatal error C1083: 无法打开包括文件: “dlfcn.h”: No such file or directory

**Comment by kmaork** [comment]
`hypno` is not supported on windows yet, as its main dependency, `pyinjector`, which is pending windows support. It shouldn't be hard but I am currently working on other things. You are welcome to open a pull request 😄 
Closing in favor of https://github.com/kmaork/pyinjector/issues/4

**Comment by Scrooge20291224** [comment]
> `hypno` is not supported on windows yet, as its main dependency, `pyinjector`, which is pending windows support. It shouldn't be hard but I am currently working on other things. You are welcome to open a pull request 😄
> Closing in favor of [kmaork/pyinjector#4](https://github.com/kmaork/pyinjector/issues/4)

Ok, I will have a try for myself first, Thx for maintaining these repo...
